version: "3"

services:
  mongodb:
    container_name: mongo
    build:
      context: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch
    environment:
      discovery.type: single-node
      ELASTICSEARCH_TLS_ENABLED: false
      ELASTIC_PASSWORD: es
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  postgres:
    container_name: psql
    build:
      context: postgres
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: psql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    build:
      context: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80"

volumes:
  mongodb-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/d/Projekty/pk-ztbd-data/mongodb"
  elasticsearch-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/d/Projekty/pk-ztbd-data/elasticsearch"
  postgres-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/d/Projekty/pk-ztbd-data/postgres"
